services:
  keepalived:
    image: osixia/keepalived:latest
    container_name: keepalived
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
#      - NET_BROADCAST
    environment:
      - KEEPALIVED_INTERFACE=eth0
      - KEEPALIVED_VIRTUAL_IPS=192.168.0.100 
      - TZ=Europe/Minsk
    volumes:
      - /DATA/AppData/keepalived/keepalived.conf:/etc/keepalived/keepalived.conf
      - /DATA/AppData/keepalived/check_adguard.sh:/usr/local/bin/check_adguard.sh:ro