name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    volumes:
      - /volume3/docker/immich/upload:/data
      - /volume1/storage/Photo:/mnt/media/Photo
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    group_add:
      - "937"        
    devices:
      - /dev/dri:/dev/dri       

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    security_opt:
      - no-new-privileges:true
    volumes:
      - /volume3/docker/immich/model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    group_add:
      - "937"        
    devices:
      - /dev/dri:/dev/dri      

      
  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9@sha256:4963247afc4cd33c7d3b2d2816b9f7f8eeebab148d29056c2ca4d7cbc966f2d9
    security_opt:
      - no-new-privileges:true    
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always 
    labels:
      - com.centurylinklabs.watchtower.enable=false

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      - /volume3/docker/immich/pgdata:/var/lib/postgresql/data
    shm_size: 128mb  
    restart: always
    healthcheck:
      disable: false    
    labels:
      - com.centurylinklabs.watchtower.enable=false
   

volumes:
  model-cache:
