services:
  glances:
    container_name: glances
    image: nicolargo/glances:latest-full
    healthcheck:
     test: curl -f http://localhost:61208/ || exit 1
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    pid: host
    privileged: true
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      GLANCES_OPT: "-w --enable-plugin smart"
      TZ: Europe/Minsk      
    restart: unless-stopped