services:
    portainer-ce:
        ports:
            - 8000:8000
            - 9443:9443        
        container_name: portainer
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /volume3/docker/portainer:/data
        image: portainer/portainer-ce:latest
        environment:
          user: 1026:100         
          TZ: Europe/Minsk  
